name: Test
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      # todo: we should commit the lock file and use npm ci
      - run: npm install
      - run: npm run build
      - run: npm run build:tests
      - run: npm run test
      - run: npm run lint
        if: always()
